create table if not exists genre (
    id integer generated by default as identity primary key,
    name varchar(100)
    );

create table if not exists mpa_rating (
    id integer generated by default as identity primary key,
    name varchar(100) NOT NULL,
    description varchar(255) NOT NULL
    );

create table if not exists film (
    id integer generated by default as identity primary key,
    name varchar(100) NOT NULL,
    description varchar(255) NOT NULL,
    release_date date NOT NULL,
    duration bigint NOT NULL,
    mpa_rating_id integer references MPA_RATING (id),
    constraint constr_film_duration check (duration>0 and name<>'')
    );

create table if not exists film_genre (
    film_id integer references FILM (ID),
    genre_id integer references GENRE (ID)
    );

create table if not exists friendship_status (
    id integer generated by default as identity primary key,
    name varchar(100) not null
    );

create table if not exists usr (
    id integer generated by default as identity primary key,
    name varchar(100) NOT NULL,
    login varchar(100) NOT NULL,
    email varchar(100) NOT NULL,
    birthday date not null
    constraint constr_usr check (email<>'' and name<>'')
    );

create table if not exists friendship (
    user_id integer references USR (ID),
    friend_id integer references USR (ID),
    friendship_status_id integer references FRIENDSHIP_STATUS (ID)
    );

create table if not exists likes (
    user_id integer references USR (ID),
    film_id integer references FILM (ID)
    )